services:
  # reverse-proxy:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  #     - elven-client
  #     - dwarven-client
  #     - human-client
  #   networks:
  #     - app-network

  api:
    build:
      context: .
      dockerfile: ${API_DOCKERFILE}
      target: dev
    container_name: api
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${API_PORT}
      - REDIS_HOST=redis
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - redis
    volumes:
      - ./apps/api/src:/app/apps/api/src
    networks:
      - app-network

  # websocket-service:
  #   build:
  #     context: ./apps/websocket-service
  #     dockerfile: Dockerfile
  #   container_name: websocket-service
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  power-client:
    build:
      context: .
      dockerfile: ${POWER_CLIENT_DOCKERFILE}
      target: dev
    container_name: power-client
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=${POWER_CLIENT_PORT}
      - API_URL=http://api:${API_PORT}
    ports:
      - "${POWER_CLIENT_PORT}:${POWER_CLIENT_PORT}"
    networks:
      - app-network

  # elven-client:
  #   build:
  #     context: ./apps/elven-client
  #     dockerfile: Dockerfile
  #   container_name: elven-client
  #   environment:
  #     - CLIENT_ID=elven
  #   networks:
  #     - app-network

  # dwarven-client:
  #   build:
  #     context: ./apps/dwarven-client
  #     dockerfile: Dockerfile
  #   container_name: dwarven-client
  #   environment:
  #     - CLIENT_ID=dwarven
  #   networks:
  #     - app-network

  # human-client:
  #   build:
  #     context: ./apps/human-client
  #     dockerfile: Dockerfile
  #   container_name: human-client
  #   environment:
  #     - CLIENT_ID=human
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
